global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using EntityId = System.Int64;
global using CrudApp.Infrastructure.Authentication;
global using CrudApp.Infrastructure.Authorization;
global using CrudApp.Infrastructure.Database;
global using CrudApp.Infrastructure.Entities;
global using CrudApp.Infrastructure.ErrorHandling;
global using CrudApp.Infrastructure.UtilityCode;
global using CrudApp.Infrastructure.Primitives;